import type { DailyJournalEntry, AccountState } from '../types';
import { DEFAULT_PROP_CONFIG } from './rules';

export const INITIAL_ACCOUNT_STATE: AccountState = {
  baseCapital: 100_000,
  currentEquity: 103_450,
  currentBalance: 103_450,
  startOfDayBalance: 103_120,
  peakRecordedEquity: 103_450,
  existingOpenRisk: 350,
  streakDays: 14,
  cycleStartDate: '2026-08-01',
  config: DEFAULT_PROP_CONFIG,
};

export const MOCK_JOURNAL_ENTRIES: DailyJournalEntry[] = [
  {
    id: 'entry-1',
    date: '2026-08-04',
    session: 'New York',
    tradesCount: 2,
    netProfit: 310,
    highestFloatingDrawdown: 65,
    lotsTraded: 1.5,
    assetsTraded: ['XAUUSD', 'BTCUSD'],
    setupGrade: 'A+',
    emotion: 'Calm',
    mistakes: ['Valid SL', 'Perfect Execution'],
    ruleBreach: false,
    notes: 'Clean 15m orderblock retest on Gold during NY Open. Took 1:2 R:R and secured profit.',
    disciplineScore: 100,
  },
  {
    id: 'entry-2',
    date: '2026-08-05',
    session: 'London',
    tradesCount: 1,
    netProfit: 275,
    highestFloatingDrawdown: 40,
    lotsTraded: 1.0,
    assetsTraded: ['XAGUSD'],
    setupGrade: 'A',
    emotion: 'Disciplined',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'London Judas swing liquidity sweep on Silver into 4H FVG. Partial at 1:1.5, runner closed at target.',
    disciplineScore: 100,
  },
  {
    id: 'entry-3',
    date: '2026-08-06',
    session: 'New York',
    tradesCount: 1,
    netProfit: -120,
    highestFloatingDrawdown: 120,
    lotsTraded: 1.2,
    assetsTraded: ['XAUUSD'],
    setupGrade: 'B',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Gold rejected 15m breaker block. SL hit as planned (-$120). Closed terminal immediately, respected soft-stop.',
    disciplineScore: 100,
  },
  {
    id: 'entry-4',
    date: '2026-08-07',
    session: 'New York',
    tradesCount: 2,
    netProfit: 340,
    highestFloatingDrawdown: 85,
    lotsTraded: 2.0,
    assetsTraded: ['BTCUSD'],
    setupGrade: 'A+',
    emotion: 'Confident',
    mistakes: ['Valid SL', 'Perfect Execution'],
    ruleBreach: false,
    notes: 'Bitcoin expansion model after Asian consolidation sweep. Locked $340.',
    disciplineScore: 100,
  },
  {
    id: 'entry-5',
    date: '2026-08-08',
    session: 'London',
    tradesCount: 2,
    netProfit: 285,
    highestFloatingDrawdown: 50,
    lotsTraded: 1.5,
    assetsTraded: ['ETHUSD'],
    setupGrade: 'A',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Ethereum discount array tap during London open. Clean textbook session.',
    disciplineScore: 95,
  },
  {
    id: 'entry-6',
    date: '2026-08-11',
    session: 'New York',
    tradesCount: 2,
    netProfit: 260,
    highestFloatingDrawdown: 90,
    lotsTraded: 1.8,
    assetsTraded: ['XAUUSD'],
    setupGrade: 'A',
    emotion: 'Disciplined',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Gold 10:00 AM NY macro liquidity tap. 1:2.2 R:R achieved.',
    disciplineScore: 100,
  },
  {
    id: 'entry-7',
    date: '2026-08-12',
    session: 'London',
    tradesCount: 1,
    netProfit: -95,
    highestFloatingDrawdown: 95,
    lotsTraded: 1.0,
    assetsTraded: ['XAGUSD'],
    setupGrade: 'B',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Silver consolidation fakeout. Small controlled loss, respected strict 1-trade limit.',
    disciplineScore: 100,
  },
  {
    id: 'entry-8',
    date: '2026-08-13',
    session: 'New York',
    tradesCount: 2,
    netProfit: 380,
    highestFloatingDrawdown: 110,
    lotsTraded: 2.2,
    assetsTraded: ['XAUUSD', 'BTCUSD'],
    setupGrade: 'A+',
    emotion: 'Confident',
    mistakes: ['Valid SL', 'Perfect Execution'],
    ruleBreach: false,
    notes: 'Gold and Bitcoin re-accumulation setups. High probability follow-through.',
    disciplineScore: 100,
  },
  {
    id: 'entry-9',
    date: '2026-08-14',
    session: 'New York',
    tradesCount: 2,
    netProfit: 290,
    highestFloatingDrawdown: 70,
    lotsTraded: 1.6,
    assetsTraded: ['ETHUSD'],
    setupGrade: 'A',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'ETH weekly profile expansion towards buy-side liquidity pool.',
    disciplineScore: 100,
  },
  {
    id: 'entry-10',
    date: '2026-08-15',
    session: 'London',
    tradesCount: 1,
    netProfit: 255,
    highestFloatingDrawdown: 35,
    lotsTraded: 1.0,
    assetsTraded: ['XAGUSD'],
    setupGrade: 'A',
    emotion: 'Disciplined',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Hit qualifying day #7 on Silver! Clean execution, closed before NY overlap.',
    disciplineScore: 100,
  },
  {
    id: 'entry-11',
    date: '2026-08-18',
    session: 'New York',
    tradesCount: 2,
    netProfit: 310,
    highestFloatingDrawdown: 80,
    lotsTraded: 1.5,
    assetsTraded: ['BTCUSD'],
    setupGrade: 'A',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Bitcoin displacement above PDH. Hit TP at 1:2.',
    disciplineScore: 95,
  },
  {
    id: 'entry-12',
    date: '2026-08-19',
    session: 'London',
    tradesCount: 2,
    netProfit: -110,
    highestFloatingDrawdown: 110,
    lotsTraded: 1.2,
    assetsTraded: ['XAUUSD'],
    setupGrade: 'B',
    emotion: 'Anxious',
    mistakes: ['Early Exit', 'Valid SL'],
    ruleBreach: false,
    notes: 'Gold market was choppy. Cut early at -$110 rather than forcing.',
    disciplineScore: 85,
  },
  {
    id: 'entry-13',
    date: '2026-08-20',
    session: 'New York',
    tradesCount: 2,
    netProfit: 330,
    highestFloatingDrawdown: 75,
    lotsTraded: 1.7,
    assetsTraded: ['XAUUSD'],
    setupGrade: 'A+',
    emotion: 'Disciplined',
    mistakes: ['Valid SL', 'Perfect Execution'],
    ruleBreach: false,
    notes: 'Trend continuation on Gold. Captured $330.',
    disciplineScore: 100,
  },
  {
    id: 'entry-14',
    date: '2026-08-21',
    session: 'New York',
    tradesCount: 2,
    netProfit: 270,
    highestFloatingDrawdown: 60,
    lotsTraded: 1.4,
    assetsTraded: ['ETHUSD'],
    setupGrade: 'A',
    emotion: 'Calm',
    mistakes: ['Valid SL'],
    ruleBreach: false,
    notes: 'Crypto rebound off 1H Bullish FVG on ETHUSD. Perfect session.',
    disciplineScore: 100,
  },
  {
    id: 'entry-15',
    date: '2026-08-22',
    session: 'London',
    tradesCount: 1,
    netProfit: 290,
    highestFloatingDrawdown: 45,
    lotsTraded: 1.0,
    assetsTraded: ['XAUUSD'],
    setupGrade: 'A+',
    emotion: 'Calm',
    mistakes: ['Valid SL', 'Perfect Execution'],
    ruleBreach: false,
    notes: 'Total accumulated profit crossed $3,450. Consistency and qualifying days 100% compliant!',
    disciplineScore: 100,
  }
];
